CMake: link systemui wrapper with qtcore
Workaround for linker issue when systemui wrapper is used from
test case and builtin test data is used. In that case, test will include
resource file that requires linking with qtbase.

Fixes bubblewrap/.qt/rcc/qrc_tst_bubblewrap_single-process_testdata_builtin.cpp:84:(.text+0x27): undefined reference to `qUnregisterResourceData`

Change-Id: If45177fb3ad6637b52149a0aea2c097e7fc3eda2
Reviewed-by: Robert Griebl <robert.griebl@qt.io>