main-lib: fix systemmonitor.h include build error
Due to a build error that occurs while running qmake recursively, the
src.pro file was modified in order to ensure that the headers are
generated in a correct order.

main.cpp:131:27: fatal error: systemmonitor.h: No such file or directory
 #include "systemmonitor.h"
                           ^

Change-Id: I541067c2202900f8408d4e28e05d8518040733e5
Reviewed-by: Robert Griebl <robert.griebl@pelagicore.com>